{{- include "sch.config.init" (list . "mqserver.sch.chart.config.values") -}}
{{- range $name, $app := .Values.global.apps.config }}
{{- if and ($app.enabled) (not (hasKey $app "mqConnectionNameList")) }}
{{- if not ($.Values.global.mq.multiInstance.operatorsEnabled) }}
---
###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: v1
kind: Service
metadata:
  name: {{ include "sch.names.fullCompName" (list $ $name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list $ $name) | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 9443
      name: console-https
    - port: 1414
      name: qmgr
  selector:
      {{- include "sch.metadata.labels.standard" (list $ $name) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
