version: 1

merge:
  whitelist:
    labels: ["merge when ready"]
    comment_substrings: ["==AUTOMERGE==", "==MERGE_WHEN_READY=="]
    branches: ["master", "epic/*"]
  blacklist:
    labels: ["do not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: merge
  delete_after_merge: true

update:
  whitelist:
    labels: ["wip", "update me"]
    branches: ["master", "epic/*"]
