version: '2.2'
services:
  db2:
    image: wh-spmdevops-docker-local.artifactory.swg-devops.com/rhel/db2:${DB2_VERSION:-11.1.3.3}
    hostname: 'db2container'
    privileged: true
    ports:
      - 50000:50000
    labels:
      InstallerBuildID: ${actualInstallerBuildId:-NotSet}
      Db2Version: ${DB2_VERSION:-11.1.3.3}
      CuramVersion: ${VERSION_VALUE}
      CuramConfiguration: ${CuramInstallation:-NotSet}
      Locale: ${Locale:-en_US}
      LangPacks: ${LangPacks:-None}
  servercode:
    build:
      context: .
      dockerfile: ServerEAR.Dockerfile
      args:
        WLP_VERSION: ${LibertyImageVersion:?'LibertyImageVersion' must be set!}
        MQ_ADAPTER_VERSION: ${MQ_ADAPTER_VERSION:-9.1.5.0}
        MQ_RA_LICENSE: --acceptLicense
      labels:
        InstallerBuildID: ${actualInstallerBuildId:-NotSet}
        LibertyImageVersion: ${LibertyImageVersion:?'LibertyImageVersion' must be set!}
        CuramVersion: ${VERSION_VALUE}
        CuramConfiguration: ${CuramInstallation:-NotSet}
        Locale: ${Locale:-en_US}
        LangPacks: ${LangPacks:-None}
    image: ${DOCKER_REGISTRY}/${CuramVersion}/${IMAGE_PREFIX:?'IMAGE_PREFIX' must be specified}_servercode:${IMAGE_TAG:-untagged}
    links:
      - db2:db2container
  wlp:
    build:
      context: .
      dockerfile: ClientEAR.Dockerfile
      args:
        EAR_NAME: ${EAR_NAME:-Curam}
        SERVERCODE_IMAGE: ${DOCKER_REGISTRY}/${CuramVersion}/${IMAGE_PREFIX:?'IMAGE_PREFIX' must be specified}_servercode:${IMAGE_TAG:-untagged}
      labels:
        InstallerBuildID: ${actualInstallerBuildId:-NotSet}
        LibertyImageVersion: ${LibertyImageVersion:?'LibertyImageVersion' must be set!}
        CuramVersion: ${VERSION_VALUE}
        CuramConfiguration: ${CuramInstallation:-NotSet}
        Locale: ${Locale:-en_US}
        LangPacks: ${LangPacks:-None}
    image: ${DOCKER_REGISTRY}/${CuramVersion}/${IMAGE_PREFIX:?'IMAGE_PREFIX' must be specified}_${IMAGE_SUFFIX:-curam}:${IMAGE_TAG:-untagged}
    links:
      - db2:db2container
  xmlserver:
    build:
      context: .
      dockerfile: XMLServer.Dockerfile
      args:
        ANT_VERSION: ${ANT_VERSION:-1.10.6}
        BASE_REGISTRY: registry.connect.redhat.com/
      labels:
        InstallerBuildID: ${actualInstallerBuildId:-NotSet}
        CuramVersion: ${VERSION_VALUE}
        CuramConfiguration: ${CuramInstallation:-NotSet}
        AntVersion: ${ANT_VERSION:-1.10.6}
        Locale: ${Locale:-en_US}
        LangPacks: ${LangPacks:-None}
    image: ${DOCKER_REGISTRY}/${CuramVersion}/${IMAGE_PREFIX:?'IMAGE_PREFIX' must be specified}_xmlserver:${IMAGE_TAG:-untagged}
  utilities:
    build:
      context: .
      dockerfile: Utilities.Dockerfile
      args:
        BASE_REGISTRY: registry.connect.redhat.com/
      labels:
        InstallerBuildID: ${actualInstallerBuildId:-NotSet}
        CuramVersion: ${VERSION_VALUE}
        CuramConfiguration: ${CuramInstallation:-NotSet}
        AntVersion: ${ANT_VERSION:-1.10.6}
        Locale: ${Locale:-en_US}
        LangPacks: ${LangPacks:-None}
    image: ${DOCKER_REGISTRY}/${CuramVersion}/${IMAGE_PREFIX:?'IMAGE_PREFIX' must be specified}_utilities:${IMAGE_TAG:-untagged}
  batch:
    build:
      context: .
      dockerfile: Batch.Dockerfile
      args:
        WLP_VERSION: ${LibertyImageVersion:?'LibertyImageVersion' must be set!}
        ANT_VERSION: ${ANT_VERSION:-1.10.6}
      labels:
        InstallerBuildID: ${actualInstallerBuildId:-NotSet}
        LibertyVersion: ${LibertyImageVersion:?'LibertyImageVersion' must be set!}
        CuramVersion: ${VERSION_VALUE}
        CuramConfiguration: ${CuramInstallation:-NotSet}
        AntVersion: ${ANT_VERSION:-1.10.6}
        Locale: ${Locale:-en_US}
        LangPacks: ${LangPacks:-None}
    image: ${DOCKER_REGISTRY}/${CuramVersion}/${IMAGE_PREFIX:?'IMAGE_PREFIX' must be specified}_batch:${IMAGE_TAG:-untagged}
    links:
      - db2:db2container
