---
###############################################################################
# The tuning values listed are for demonstration purposes only. 
# These values are a suggested starting point and are not definitive. 
# Customers should perform their own testing, to validate and verify their own
# settings, in order to meet their system needs.
###############################################################################
global:
  license: '' # Set to 'accept' after reviewing all license agreements
  images:
    registry: us.icr.io
    imageLibrary: foo-library
    imagePrefix: test_
    imageTag: latest
    pullPolicy: Always
  imagePullSecret:
    registry: us.icr.io
    username: '' # IAM username for IBM Container Registry
    password: '' # IAM API Key for IBM Container Registry
  database:
    ## Database connection properties
    type: DB2
    dbName: DATABASE
    hostname: ''
    port: 50000
    username: db2admin
    # Name of pre-created secret containing database credentals
    credsSecretName: ''
    # The XOR-encrypted password injected into Liberty configuration
    wlp_psw: "{xor}Oz1tPjsyNjE="
    # The SPM-encrypted password injected into Bootstrap.properties
    spm_psw: "5itAmT5UzH7wR6kvkYqkTw=="
    # Oracle Service name, where applicable
    serviceName: ''
    ssl:
      enabled: false
      # Name of the secret containing the database TLS certificate
      secretName: ''
      # Key in the above secret with the certificate
      secretKey: db2admin.arm
  ingress:
    annotations:
      ingress.bluemix.net/ALB-ID: ''
    enabled: true
    hostname: spm.<cluster_name>-<hash>-0000.<region>.containers.appdomain.cloud
    tlsSecretName: default-us-icr-io
  apps: {}
    # config:
    #   curam:
    #     enabled: true
    #     resources:
    #       limits:
    #         cpu: 2
    #         memory: 4Gi
    #       requests:
    #         cpu: 1
    #         memory: 2Gi
    #     producerTuning: 
    #       # Curam Producer JVM Setting
    #       jvm: ['-Xms1844M','-Xmx1844M','-Xmn1228M']
    #       coreThreads: 4
    #       maxThreads: 4
    #       maxPoolSize: 8
    #       numConnectionsPerThreadLocal: 2
    #       purgePolicy: EntirePool
    #       statementCacheSize: 1000
    #       # MQ Settings for Curam Producer
    #       mqMaxPoolSize: 8
    #       mqMinPoolSize: 8
    #       mqNumConnectionsPerThreadLocal: 2
    #       maxJMSConnectionsPerThread: 2
    #       maxEndPoints_DPErrorAS: 1
    #       maxEndPoints_WorkflowErrorAS: 1
    #       maxEndPoints_CuramDeadMessageQueueAS: 1
    #       maxEndPoints_DPEnactmentAS: 100
    #       maxEndPoints_WorkflowActivityAS: 101
    #       maxEndPoints_WorkflowEnactmentAS: 102
    #       # Curam Producer Database Settings
    #       curamdb_maxPoolSize: 16
    #       curamdb_numConnectionsPerThreadLocal: 2
    #       curamdb_purgePolicy: EntirePool
    #       curamdb_statementCacheSize: 1000
    #       curamtimerdb_maxPoolSize: 8
    #       curamtimerdb_numConnectionsPerThreadLocal: 2
    #       curamtimerdb_purgePolicy: EntirePool
    #       curamtimerdb_statementCacheSize: 1000
    #       curamsessdb_maxPoolSize: 8
    #       curamsessdb_numConnectionsPerThreadLocal: 2
    #       curamsessdb_purgePolicy: EntirePool
    #       curamsessdb_statementCacheSize: 1000
    #       # Curam Producer requested resources
    #       resources:
    #         requests:
    #           cpu: 2
    #           memory: 2850Mi
    #         limits:
    #           cpu: 2
    #           memory: 2850Mi
    #     consumerTuning:
    #       # Curam Consumer JVM Setting
    #       jvm: ['-Xms1844M','-Xmx1844M','-Xmn1228M']
    #       coreThreads: 4
    #       maxThreads: 4
    #       maxPoolSize: 8
    #       numConnectionsPerThreadLocal: 2
    #       purgePolicy: EntirePool
    #       statementCacheSize: 1000
    #       # MQ Settings for Curam Consumer
    #       mqMaxPoolSize: 12
    #       mqMinPoolSize: 12
    #       mqNumConnectionsPerThreadLocal: 2
    #       maxJMSConnectionsPerThread: 2
    #       maxEndPoints_DPErrorAS: 1
    #       maxEndPoints_WorkflowErrorAS: 1
    #       maxEndPoints_CuramDeadMessageQueueAS: 1
    #       maxEndPoints_DPEnactmentAS: 100
    #       maxEndPoints_WorkflowActivityAS: 101
    #       maxEndPoints_WorkflowEnactmentAS: 102
    #       # Curam Consumer Database Settings
    #       curamdb_maxPoolSize: 24
    #       curamdb_numConnectionsPerThreadLocal: 2
    #       curamdb_purgePolicy: EntirePool
    #       curamdb_statementCacheSize: 1000
    #       curamtimerdb_maxPoolSize: 12
    #       curamtimerdb_numConnectionsPerThreadLocal: 2
    #       curamtimerdb_purgePolicy: EntirePool
    #       curamtimerdb_statementCacheSize: 1000
    #       curamsessdb_maxPoolSize: 12
    #       curamsessdb_numConnectionsPerThreadLocal: 2
    #       curamsessdb_purgePolicy: EntirePool
    #       curamsessdb_statementCacheSize: 1000
    #       # Curam Consumer requested resources
    #       resources:
    #         requests:
    #           cpu: 2
    #           memory: 2850Mi
    #         limits:
    #           cpu: 2v
    #           memory: 2850Mi
    #       mqTuning:
    #         resources:
    #           requests:
    #             cpu: 1
    #             memory: 2300Mi
    #           limits:
    #             cpu: 1.5
    #             memory: 2500Mi
    #   rest:
    #     enabled: true
    #     resources:
    #       limits:
    #         cpu: 2
    #         memory: 4Gi
    #       requests:
    #         cpu: 1
    #         memory: 2Gi
    #     producerTuning:
    #       # Rest Producer JVM Setting
    #       jvm: ['-Xms2304M','-Xmx2304M','-Xmn1536M']
    #       coreThreads: 8
    #       maxThreads: 8
    #       # MQ Settings for Rest Producer
    #       mqMaxPoolSize: 8
    #       mqMinPoolSize: 8
    #       mqNumConnectionsPerThreadLocal: 2
    #       maxJMSConnectionsPerThread: 2
    #       maxEndPoints_DPErrorAS: 1
    #       maxEndPoints_WorkflowErrorAS: 1
    #       maxEndPoints_CuramDeadMessageQueueAS: 1
    #       maxEndPoints_DPEnactmentAS: 100
    #       maxEndPoints_WorkflowActivityAS: 101
    #       maxEndPoints_WorkflowEnactmentAS: 102
    #       # Rest Producer Database Settings
    #       curamdb_maxPoolSize: 16
    #       curamdb_numConnectionsPerThreadLocal: 2
    #       curamdb_purgePolicy: EntirePool
    #       curamdb_statementCacheSize: 1000
    #       curamtimerdb_maxPoolSize: 8
    #       curamtimerdb_numConnectionsPerThreadLocal: 2
    #       curamtimerdb_purgePolicy: EntirePool
    #       curamtimerdb_statementCacheSize: 1000
    #       curamsessdb_maxPoolSize: 8
    #       curamsessdb_numConnectionsPerThreadLocal: 2
    #       curamsessdb_purgePolicy: EntirePool
    #       curamsessdb_statementCacheSize: 1000
    #       # Rest Producer requested resources
    #       resources:
    #         requests:
    #           cpu: 2
    #           memory: 3300Mi
    #         limits:
    #           cpu: 2
    #           memory: 3300Mi
    #     consumerTuning:
    #       # Rest Consumer JVM Setting
    #       jvm: ['-Xms6G','-Xmx6G','-Xmn4G']
    #       coreThreads: 12
    #       maxThreads: 12
    #       # MQ Settings for Rest Consumer
    #       mqMaxPoolSize: 12
    #       mqMinPoolSize: 12
    #       mqNumConnectionsPerThreadLocal: 2
    #       maxJMSConnectionsPerThread: 2
    #       maxEndPoints_DPErrorAS: 1
    #       maxEndPoints_WorkflowErrorAS: 1
    #       maxEndPoints_CuramDeadMessageQueueAS: 1
    #       maxEndPoints_DPEnactmentAS: 100
    #       maxEndPoints_WorkflowActivityAS: 101
    #       maxEndPoints_WorkflowEnactmentAS: 102
    #       # Rest Consumer Database Settings
    #       curamdb_maxPoolSize: 24
    #       curamdb_numConnectionsPerThreadLocal: 2
    #       curamdb_purgePolicy: EntirePool
    #       curamdb_statementCacheSize: 1000
    #       curamtimerdb_maxPoolSize: 12
    #       curamtimerdb_numConnectionsPerThreadLocal: 2
    #       curamtimerdb_purgePolicy: EntirePool
    #       curamtimerdb_statementCacheSize: 1000
    #       curamsessdb_maxPoolSize: 12
    #       curamsessdb_numConnectionsPerThreadLocal: 2
    #       curamsessdb_purgePolicy: EntirePool
    #       curamsessdb_statementCacheSize: 1000
    #       # Rest Consumer requested resources
    #       resources:
    #         requests:
    #           cpu: 2
    #           memory: 6400Mi
    #         limits:
    #           cpu: 2
    #           memory: 6400Mi
    #   citizenportal:
    #     enabled: false
    #   curamwebservices:
    #     enabled: false
    #   curambirtviewer:
    #     enabled: false

# Override values in 'apps' Chart
apps: {}
#   replicaCount: 1
#   initialDelaySeconds: 60
#   loginConfig:
#     trace: true
#   sessionConfig:
#     sessionTimeout: 30m
#     transactionTimeout: 3m
#   defaultResources:
#     requests:
#       cpu: 0.5
#       memory: 768Mi
#     limits:
#       cpu: 0.75
#       memory: 1Gi

# Override values in 'batch' Chart
batch: {}
#   programs:
#     queued:
#       schedule: "*/30 * * * *"

# Override values in 'uawebapp' Chart
uawebapp: {}
#   replicaCount: 1
#   imageConfig:
#     library: ''
#     name: ''
#     tag: latest
#   readinessProbe:
#     path: /universal/
#   ingressPath: /universal
#   resources:
#     requests:
#       cpu: 2
#       memory: 1000Mi
#     limits:
#       cpu: 2
#       memory: 1000Mi

# Override values in 'web' Chart
web: {}
#   replicaCount: 1
#   readinessProbe:
#     path: /CuramStatic/
#   ingressPath: /CuramStatic
#   resources:
#     requests:
#       cpu: 2
#       memory: 1000Mi
#     limits:
#       cpu: 2
#       memory: 1000Mi

# Override values in 'xmlserver' Chart
xmlserver: {}
#   replicaCount: 1
#   jvm:
#      maxMemory: '-Djava.maxmemory=768m'
#      threadStackSize: '-Djava.thread.stack.size=-Xss4m'
#   config:
#      socketTimeout: 60000
#      threadPoolQueueSize: 200
#      threadPoolSize: 6
#   resources:
#     requests:
#       cpu: 2
#       memory: 1000Mi
#     limits:
#       cpu: 2
#       memory: 1000Mi
