{{- include "sch.config.init" (list . "xmlserver.sch.chart.config.values") -}}
---
###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sch.names.fullName" (list .) }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sch.metadata.labels.standard" (list . "") | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sch.names.appName" (list .) | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . "") | indent 8 }}
    spec:
{{- include "sch.security.securityContext" (list . .sch.chart.podSecurityContext) | indent 6 }}
      affinity:
{{- include "sch.affinity.nodeAffinity" (list . .sch.chart.nodeAffinity) | indent 8 }}
      restartPolicy: {{ .restartPolicy | default "Always" }}
      {{- if or .Values.global.imagePullSecret.secretName .Values.global.imagePullSecret.username }}
      imagePullSecrets:
        - name: {{ default (printf "%s-pull-secret" .Release.Name) .Values.global.imagePullSecret.secretName }}
      {{- end }}
      serviceAccountName: {{ default (include "sch.names.fullName" (list .)) .Values.serviceAccountName }}
      {{- if .Values.global.apps.common.persistence.enabled }}
      volumes:
        - name: {{ .Release.Name }}-persistence-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-persistence-pvc
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "xmlserver.imageFullName" .Values.global.images }}
          imagePullPolicy: {{ .Values.global.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.serverPort | default 1800 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- include "sch.security.securityContext" (list . .sch.chart.containerSecurityContext) | indent 10 }}
          {{- if .Values.global.apps.common.persistence.enabled }}
          env:
            - name: TZ
              value: {{ .Values.global.timezone }}
            - name: MOUNT_POINT
              value: {{ include "persistence.mountPoint" $ }}
          volumeMounts:
            - name: {{ .Release.Name }}-persistence-volume
              mountPath: {{ include "persistence.mountPoint" $ }}
              subPath: {{ include "persistence.subDir" $ }}
          {{- end }}
